title: Krzysztof Zadka # your name (or website title) here
logo: "/images/Official.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently I'm on the course Data Science from PFIG and I'm discovering the fascinating world of Big Data and AI. 
  Thanks to my previous professional experience I am organized, accurate and able to pay attention to details. 
  <br><br>
  <a href="https://www.linkedin.com/in/krzysztof-zadka/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/KZadka">View My GitHub Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
